version: '3'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: localpostgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    restart: always